name: practice_22
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.0
  url_launcher: ^6.0.9  
  native_pdf_view: ^4.1.0
  dio: ^4.0.0
  path_provider: ^2.0.2
  webview_flutter: ^2.0.10
  io: ^1.0.3
  convert: ^3.0.1
  sqflite: ^2.0.0+3
  animated_theme_switcher: ^2.0.1
  get_storage: ^2.0.2
  google_fonts: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/sohel.jpg
    - assets/images/sohel.pdf
    - assets/json/sample.json

    